security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: ${EXPIRE_LENGTH}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitness_tracking?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

    show-sql: false

  logging:
    level:
      org.springframework.security: DEBUG
  main:
    allow-bean-definition-overriding: true