security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitness_tracking?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

    show-sql: false

springdoc:
  pathsToMatch:
    -/product/v1/**
    -/category/v1/**
    -/cartItems/v1/**

  logging:
    level:
      org.springframework.security: DEBUG
