name: Continuous Integration with Github, Github Actions, and Docker Hub

on:
  push:
    branches: "main"

  workflow_dispatch:
    inputs:
      use-cache:
        description: "Whether to execute cache step"
        type: boolean
        default: true
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

        - name: Checkout code
          uses: actions/checkout@v4
        

        - name: Set up JDK 21 and cache
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'
            cache-dependency-path: 'pom.xml'
        

        - name: Restore Maven Cache
          id: cache
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    

        - name: Install dependencies
          run: ./mvnw clean install
          if: ${{ steps.cache.outputs.cache-hit != 'true' }}
    
        - name: Run Tests
          run: ./mvnw test
      
        - name: Build Jar Package
          run: ./mvnw package

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: guilhermebauer/fitness_tracking_status:latest
            context: .
            file: ./Dockerfile

