name: Deploy in Docker Hub

on:
  push:
    branches: "main"
  

jobs:

  install-deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.cache_key }}
    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' 
      
      - name: Calculate cached dependencies key
        id: cache-key
        run: |
          echo "cache_key=deps-maven-${{ hashFiles('pom.xml') }}" >> $GITHUB_ENV

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Install dependencies
        run: mvn clean install
        if: steps.cache.outputs.cache-hit != 'true'


  build:
    runs-on: ubuntu-latest
    needs: 
     - install-deps

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' 
          
      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
          

      - name: Building
        run: mvn package

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          # tags: ${{ secrets.DOCKER_USERNAME }}/fitness_tracking_status:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          context: .
          file: ./Dockerfile



