name: Continuous Integration with Github, Github Actions, and Docker Hub

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build Application Jar
      run: mvn clean package

    - name: Docker Compose Build
      run: docker compose build

    - name: List Docker Images
      run: docker images

    - name: Tag and Push Docker Image
      run: |
        docker tag fitness_tracking:latest guilhermebauer/fitness_tracking:latest
        docker push guilhermebauer/fitness_tracking:latest
