name: Continuous Integration with Github, Github Actions, and Docker Hub  

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application Jar
      working-directory: .
      run: mvn clean package
      
    - name: Docker Compose Build 
      working-directory: .
      run: docker compose build
      
    - name: List Docker Images
      run: docker images

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/fitness_tracking:latest ${{ secrets.DOCKER_USERNAME }}/fitness_tracking:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/fitness_tracking:${{ github.run_id }} ${{ secrets.DOCKER_USERNAME }}/fitness_tracking:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/fitness_tracking:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/fitness_tracking:${{ github.run_id }}
